# Generated by Django 5.1.2 on 2026-01-03 13:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calle', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('piso', models.CharField(blank=True, max_length=10, null=True)),
                ('otros', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_postal', models.DecimalField(decimal_places=0, max_digits=5)),
                ('pais', models.CharField(default='España', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=200)),
                ('telefono', models.DecimalField(decimal_places=0, max_digits=9)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('documento_identidad', models.CharField(max_length=9, null=True, unique=True)),
                ('direccion', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_legal', to='socios.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ROOT', 'Superusuario'), ('ADMIN', 'Directivo'), ('USER', 'Usuario')], default='USER', max_length=5)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.DecimalField(decimal_places=0, max_digits=9)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('menor_edad', models.BooleanField()),
                ('domicilia_pago', models.BooleanField(default=True)),
                ('IBAN', models.CharField(blank=True, max_length=34, null=True)),
                ('documento_identidad', models.CharField(max_length=9, null=True, unique=True)),
                ('direccion', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socio', to='socios.direccion')),
                ('tutor_legal', models.ManyToManyField(blank=True, null=True, related_name='socios', to='socios.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('anio', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('cuota_base_aplicada', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('EN_TRAMITE', 'En tramite'), ('DEVUELTO', 'Devuelto')], default='PENDIENTE', max_length=12)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='socios.socio')),
            ],
            options={
                'ordering': ['-anio', '-mes'],
                'unique_together': {('socio', 'mes', 'anio')},
            },
        ),
    ]
