# Generated by Django 5.2.9 on 2025-12-10 15:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_direccion_socio_documento_identidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('anio', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('cuota_base_aplicada', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('EN_TRAMITE', 'En tramite'), ('DEVUELTO', 'Devuelto')], default='PENDIENTE', max_length=12)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='socios.socio')),
            ],
            options={
                'ordering': ['-anio', '-mes'],
                'unique_together': {('socio', 'mes', 'anio')},
            },
        ),
    ]