# Generated by Django 5.2.9 on 2025-12-11 10:33
# # socios/migrations/0004_seed_final.py

from django.db import migrations
from django.conf import settings
from datetime import date
from decimal import Decimal
import uuid

def seed_socios_y_pagos(apps, schema_editor):
    """Crea socios y pagos solo en desarrollo"""
    
    if not settings.DEBUG:
        print("⚠️ Seed omitido: DEBUG=False")
        return
    
    Socio = apps.get_model('socios', 'Socio')
    Direccion = apps.get_model('socios', 'Direccion')
    Pago = apps.get_model('socios', 'Pago')
    
    # Evitar duplicados
    if Socio.objects.filter(email='ana@example.com').exists():
        print("⚠️ Seed ya ejecutado, saltando")
        return
    
    print("🚀 Creando datos de prueba...")
    
    # SOCIO 1: Domiciliado - Pagos completos desde 2022
    dir1 = Direccion.objects.create(
        calle='Calle Mayor', numero='15', ciudad='Zaragoza',
        provincia='Zaragoza', codigo_postal=50001, pais='España'
    )
    socio1 = Socio.objects.create(
        id=uuid.uuid4(), nombre='Ana', apellidos='García',
        email='ana@example.com', role='ADMIN',
        fecha_nacimiento=date(1985, 3, 15), telefono=612345678,
        documento_identidad='12345678A', menor_edad=False,
        domicilia_pago=True, IBAN='ES9121000418450200051332',
        direccion=dir1
    )
    
    # Pagos 2022-2025
    for year in [2022, 2023, 2024, 2025]:
        for month in range(1, 13):
            if year == 2025 and month > date.today().month:
                break
            Pago.objects.create(
                socio=socio1, mes=month, anio=year,
                cuota_base_aplicada=Decimal('50.00'),
                estado='DEVUELTO' if month % 5 == 0 else 'COMPLETADO'
            )
    
    # SOCIO 2: Sin domiciliar - Pagos desde abril 2024
    dir2 = Direccion.objects.create(
        calle='San Miguel', numero='7', ciudad='Zaragoza',
        provincia='Zaragoza', codigo_postal=50002, pais='España'
    )
    socio2 = Socio.objects.create(
        id=uuid.uuid4(), nombre='Miguel', apellidos='Aparicio',
        email='miguel@example.com', role='USER',
        fecha_nacimiento=date(1982, 4, 10), telefono=645789123,
        documento_identidad='56789012E', menor_edad=False,
        domicilia_pago=False, IBAN='', direccion=dir2
    )
    
    # Pagos desde abril 2024
    for year in [2024, 2025]:
        start_month = 4 if year == 2024 else 1
        end_month = date.today().month if year == 2025 else 12
        for month in range(start_month, end_month + 1):
            Pago.objects.create(
                socio=socio2, mes=month, anio=year,
                cuota_base_aplicada=Decimal('50.00'),
                estado='COMPLETADO' if month <= 8 else 'PENDIENTE'
            )
    
    print("✅ Creados 2 socios con pagos")
    print(f"   - Ana: {socio1.pagos.count()} pagos")
    print(f"   - Miguel: {socio2.pagos.count()} pagos")

def reverse(apps, schema_editor):
    """Elimina datos de prueba"""
    Socio = apps.get_model('socios', 'Socio')
    Direccion = apps.get_model('socios', 'Direccion')
    Pago = apps.get_model('socios', 'Pago')
    
    emails = ['ana@example.com', 'miguel@example.com']
    socios = Socio.objects.filter(email__in=emails)
    Pago.objects.filter(socio__in=socios).delete()
    dirs = [s.direccion_id for s in socios]
    socios.delete()
    Direccion.objects.filter(id__in=dirs).delete()
    print("🗑️  Datos de seed eliminados")

class Migration(migrations.Migration):
    dependencies = [
        ("socios", "0003_pago"),
    ]
    
    operations = [
        migrations.RunPython(seed_socios_y_pagos, reverse),
    ]