# Generated by Django 5.2.9 on 2026-01-01 17:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0004_seed_datos_reales'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
